### PR TITLE
fix: fix return value of janus-idp.hostname

### LINKED ISSUE #97: bug: `janus-idp.hostname` is not returning correct value
The default `baseUrl` value in `values.yaml` (`baseUrl: 'https://{{- include "janus-idp.hostname" . }}'`) doesn't render the correct hostname when `clusterRouteBase`  is set.

- Deployed Janus chart with release name `janus`. 
  - Route name is `janus-backstage`
  - Route host is `janus-backstage-janus.<clusterRouterBase>`
  - janus-idp.hostname is `janus-janus.<clusterRouterBase>`

Temporary workaround is to set baseUrl manually

### PR DESCRIPTION
**Pull request by Zaperex**
## Description of the change

Fixed the helm chart's helper template so that the `janus-idp.hostname` returns the correct value that matches the route host when the `clusterRouterBase` is defined.
## Existing or Associated Issue(s)

Fixes #97 
## Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the `values.yaml` and added to the README.md. The [pre-commit](https://pre-commit.com/) utility can be used to generate the necessary content. Use `pre-commit run -a` to apply changes.
- [ ] JSON Schema template updated and re-generated the raw schema via `pre-commit` hook.
- [x] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

### CODE REVIEW

**Comment by Zaperex** [comment]
I think the CI tests are failing since the helm chart is currently pulling the `quay.io/janus-idp/backstage-showcase:latest` which currently doesn't work with the default configurations.

This is most likely by the `test-connection` pod is unable to get a response from the backstage deployment pod since the pod has already stopped due to the backend failing to start up.
https://github.com/janus-idp/helm-backstage/actions/runs/6357218000/job/17268048606?pr=116#step:10:175

**Comment by Zaperex** [comment]
I ran the `ct install --config ct-install.yaml` locally after changing the image in the values.yaml to `quay.io/janus-idp/backstage-showcase:nightly-20230929` and it passed.

**Comment by kadel** [comment]
@Zaperex If you rebase with the current `main` branch, it should fix the testing issue.

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
