### PR TITLE
chore(ci): test with latest and next showcase images

### PR DESCRIPTION
**Pull request by kadel**
## Description of the change

- https://github.com/janus-idp/backstage-showcase/issues/545 got fixed, so we can revert to using the regular `latest` tag
- this also adds new test using `next` tag to validate that this chart is compatible with the next release (main branch)

## Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the `values.yaml` and added to the README.md. The [pre-commit](https://pre-commit.com/) utility can be used to generate the necessary content. Use `pre-commit run -a` to apply changes.
- [ ] JSON Schema template updated and re-generated the raw schema via `pre-commit` hook.
- [ ] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

### CODE REVIEW

**Comment by kadel** [comment]
@tumido, what do you think about this?

**Comment by tumido** [comment]
@kadel , do we want to potentially run all tests against both images or is this just one test case? 

If it is just one test case, we should define it as one instead by adding a values file into this folder:

https://github.com/janus-idp/helm-backstage/tree/main/charts/backstage/ci

**Comment by kadel** [comment]
All tests against both images. I want to make sure that updates to this helm chart are not somehow incompatible with Janus current and future releases.

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
