### PR TITLE
Fix typo README.md

### PR DESCRIPTION
**Pull request by Zaperex**
## Description of the change

Fixed typo in the README.md
## Existing or Associated Issue(s)
N/A

## Additional Information

 
N/A
## Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the `values.yaml` and added to the README.md. The [pre-commit](https://pre-commit.com/) utility can be used to generate the necessary content. Use `pre-commit run -a` to apply changes.
- [ ] JSON Schema template updated and re-generated the raw schema via `pre-commit` hook.
- [ ] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

### CODE REVIEW

**Review by schwesig — APPROVED** [review]
/lgtm
/approve

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Comment by tumido** [comment]
Please bump the version of the chart to `2.2.2` to make it pass tests

https://github.com/janus-idp/helm-backstage/blob/729b2f6764d792ce14d8cb4a2564952852736a5d/charts/backstage/Chart.yaml#L45

**Review by tumido — CHANGES_REQUESTED** [review]
see above

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
